# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 00:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_localflavor_us.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(default='Wells Fargo', max_length=50)),
                ('name', models.CharField(default='Account', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dwolla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(default='customer id', max_length=100)),
                ('source_id', models.CharField(default='funding source', max_length=100)),
                ('status', models.SmallIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('description', models.CharField(default='expense', max_length=200)),
                ('name', models.CharField(default='group name', max_length=100)),
                ('status', models.SmallIntegerField(default=1)),
                ('split', models.SmallIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('memo', models.CharField(default='group transfer', max_length=200)),
                ('transfer', models.SmallIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.SmallIntegerField(default=1)),
                ('friends', models.SmallIntegerField(default=1)),
                ('expenses', models.SmallIntegerField(default=1)),
                ('searchable', models.SmallIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SynapseAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(default='1234567890', max_length=200)),
                ('cip_tag', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SynapseUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField()),
                ('cip_tag', models.IntegerField()),
                ('link', models.CharField(default='https://uat-api.synapsefi.com/v3.1', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(default='account', max_length=150)),
                ('transfer', models.CharField(default='accont', max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('memo', models.CharField(default='memo', max_length=200)),
                ('frequency', models.SmallIntegerField(default=1)),
                ('status', models.SmallIntegerField(default=1)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('memo', models.CharField(default='money transfer', max_length=200)),
                ('transfer', models.SmallIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='group',
        ),
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='type',
        ),
        migrations.RemoveField(
            model_name='group',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='group',
            name='member_count',
        ),
        migrations.RemoveField(
            model_name='group',
            name='type',
        ),
        migrations.RemoveField(
            model_name='member',
            name='type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='seen',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='public',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user2',
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='group_ref',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='reference',
            field=models.CharField(default='omar', max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='friend',
            name='category',
            field=models.SmallIntegerField(choices=[('1', 'default'), ('2', 'friend'), ('3', 'family'), ('4', 'favorite')], default=1),
        ),
        migrations.AddField(
            model_name='group',
            name='count',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='reference_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='funding',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.SmallIntegerField(choices=[('1', 'member'), ('2', 'host')], default=1),
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='bio', max_length=220),
        ),
        migrations.AddField(
            model_name='profile',
            name='dwolla_id',
            field=models.CharField(default='https://api-sandbox.dwolla.com', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='first', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='last', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(default='street address', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='synapse_id',
            field=models.CharField(default='123456789', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.IntegerField(default=12345),
        ),
        migrations.AddField(
            model_name='request',
            name='requested',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.CharField(default='current user', max_length=22),
        ),
        migrations.AlterField(
            model_name='activity',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tab.Group'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.SmallIntegerField(choices=[('1', 'default'), ('2', 'blocked')], default=1),
        ),
        migrations.AlterField(
            model_name='friend',
            name='user',
            field=models.CharField(default='current user', max_length=22),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.SmallIntegerField(choices=[('1', 'active'), ('2', 'didabled'), ('3', 'suspended')], default=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tab.Group'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='city', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default='1950-01-01'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=django_localflavor_us.models.USStateField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('AA', 'Armed Forces Americas'), ('AE', 'Armed Forces Europe'), ('AP', 'Armed Forces Pacific'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='CA', max_length=2),
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AddField(
            model_name='groupbalance',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tab.Group'),
        ),
        migrations.AddField(
            model_name='groupbalance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tab.Group'),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
