# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0003_auto_20170617_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
