# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0004_activity_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AlterField(
            model_name='friend',
            name='category',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
