# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0006_auto_20171018_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='group',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
