# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 00:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tab', '0007_auto_20171018_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='some action', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tab.Expense')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tab.Group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=150, null=True)),
                ('description', models.CharField(default='some action', max_length=200)),
                ('status', models.SmallIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='groupbalance',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupbalance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userbalance',
            name='user',
        ),
        migrations.DeleteModel(
            name='GroupBalance',
        ),
        migrations.DeleteModel(
            name='UserBalance',
        ),
    ]
