# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0008_auto_20170903_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='synapse_id',
            field=models.CharField(default=0, max_length=220),
        ),
    ]
