# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0009_groupactivity_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupactivity',
            name='accepted',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='groupactivity',
            name='validation',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tab.Group'),
        ),
    ]
