# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0010_auto_20170914_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.IntegerField(default=12345),
        ),
    ]
