# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0011_auto_20171027_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='reference',
            field=models.IntegerField(default='101'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='reference',
            field=models.IntegerField(default='101', null=True),
        ),
    ]
