# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0013_expense_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.CharField(default='username', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='reference',
            field=models.IntegerField(default='101', null=True),
        ),
    ]
