# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0014_auto_20171028_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='validation',
            field=models.SmallIntegerField(default=1),
        ),
    ]
