# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0014_auto_20170919_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwolla',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
