# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 23:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tab', '0015_dwolla_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynapseUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField()),
                ('cip_tag', models.IntegerField()),
                ('link', models.CharField(default='https://uat-api.synapsefi.com/v3.1', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='synapse_id',
            field=models.CharField(default='123456789', max_length=200),
        ),
    ]
