# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0016_auto_20170921_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='reference',
            field=models.CharField(default='omar', max_length=100),
        ),
    ]
