# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0018_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='split',
            field=models.SmallIntegerField(default=1),
        ),
    ]
