# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0019_expense_split'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='group',
        ),
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='group',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='record',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
